version: "3.0"

services:
  erigon:
    build: .
    container_name: erigon
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "42069:42069/tcp"
      - "42069:42069/udp"
      - 9090:9090
      - 8551:8551
    restart: always
    volumes:
      - ./data:/data
    command: /erigon/erigon --datadir=/data --chain=dev --port=30303 --http=false --authrpc.port=8551 --private.api.addr=0.0.0.0:9090 --http.api=eth,debug,net,trace,web3,erigon --mine
  rpcdaemon:
    build: .
    container_name: rpcdaemon
    depends_on:
      - erigon
    pid: service:erigon
    ports:
      - 8545:8545
      - 8546:8546
    restart: always
    volumes:
      - ./data:/data
    command: /erigon/rpcdaemon --datadir=/data --private.api.addr=erigon:9090 --http.addr 0.0.0.0 --http.port 8545 --http.api=eth,erigon,web3,net,debug,trace,txpool,parity --ws
  erigon_node2:
    build: .
    container_name: erigon_node2
    depends_on:
      - erigon
    ports:
      - 9091:9091
      - 8552:8552
    restart: always
    command: /erigon/erigon --datadir=dev2 --chain=dev --staticpeers="enode://ef2e9e8b99d22e5bd520b0b9d2f43b7531463e246ba4f7d4470b0ff47274663a11e4844e666a042dcdd425b96dbe756e536a396d6017b518c67f1c8783bcb9a2@erigon:30303" --p2p.allowed-ports=30303,30304,30305,30306,30307,30308,30309,30310 --authrpc.port=8552 --private.api.addr=127.0.0.1:9091 --nodiscover
  erigon_node3:
    build: .
    container_name: erigon_node3
    depends_on:
      - erigon
    ports:
      - 9092:9092
      - 8553:8553
    restart: always
    command: /erigon/erigon --datadir=dev3 --chain=dev --staticpeers="enode://ef2e9e8b99d22e5bd520b0b9d2f43b7531463e246ba4f7d4470b0ff47274663a11e4844e666a042dcdd425b96dbe756e536a396d6017b518c67f1c8783bcb9a2@erigon:30303" --p2p.allowed-ports=30303,30304,30305,30306,30307,30308,30309,30310 --authrpc.port=8553 --private.api.addr=127.0.0.1:9092 --nodiscover
  erigon_node4:
    build: .
    container_name: erigon_node4
    depends_on:
      - erigon
    ports:
      - 9093:9093
      - 8554:8554
    restart: always
    command: /erigon/erigon --datadir=dev4 --chain=dev --staticpeers="enode://ef2e9e8b99d22e5bd520b0b9d2f43b7531463e246ba4f7d4470b0ff47274663a11e4844e666a042dcdd425b96dbe756e536a396d6017b518c67f1c8783bcb9a2@erigon:30303" --p2p.allowed-ports=30303,30304,30305,30306,30307,30308,30309,30310 --authrpc.port=8554 --private.api.addr=127.0.0.1:9093 --nodiscover